name: agentic-rag-second-brain
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - pandas
  - pip:
      - python-dotenv
      - pydantic
      - pydantic-settings
      - llama-index
      - llama-index-vector-stores-chroma
      - chromadb
      - openai
      - notebook

